development:
  dialect: mysql
  database: coke_development
  user: root
  password: root
  host: localhost
  port: 3306

test:
  url: {{envOr "TEST_DATABASE_URL" "mysql://root:root@localhost:3306/coke_development"}}

production:
  url: {{envOr "DATABASE_URL" "mysql://root:root@localhost:3306/coke_production"}}